# Generated by Django 5.2.8 on 2025-12-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
